# Generated by Django 5.1.5 on 2025-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
