# Generated by Django 5.1.5 on 2025-04-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_documents_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='signature',
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signature/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
