# Generated by Django 5.1.5 on 2025-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_documents_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
