# Generated by Django 5.1.5 on 2025-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_farmerprofile_is_verfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
