# Generated by Django 5.1.5 on 2025-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_farmerprofile_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
