# Generated by Django 5.1.5 on 2025-04-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contractorprofile_is_verfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorprofile',
            name='is_verfied',
        ),
    ]
