# Generated by Django 5.1.5 on 2025-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_contractorprofile_is_verfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='is_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
