# Generated by Django 5.1.5 on 2025-03-10 05:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_documents_doc_alter_profile_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_image',
            field=models.FileField(blank=True, null=True, upload_to='aadhar/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
