# Generated by Django 5.1.5 on 2025-03-07 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('crop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=256)),
                ('crop_image', models.ImageField(upload_to='crop_images/')),
                ('crop_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('Description', models.TextField(max_length=200)),
                ('harvested_time', models.DateTimeField()),
                ('location', models.TextField(max_length=150)),
                ('market_price', models.IntegerField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
