# Generated by Django 5.1.5 on 2025-03-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='market_price',
        ),
    ]
