# Generated by Django 5.1.5 on 2025-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_remove_crops_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='harvested_time',
            field=models.DateField(),
        ),
    ]
