# Generated by Django 5.1.5 on 2025-03-12 05:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_alter_crops_harvested_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='crop_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
