# Generated by Django 5.1.5 on 2025-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='term',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AdditionalTerms',
        ),
    ]
