# Generated by Django 5.1.5 on 2025-04-02 07:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_term_delete_additionalterms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='term',
        ),
        migrations.AddField(
            model_name='contract',
            name='terms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
