# Generated by Django 5.1.5 on 2025-03-16 17:20

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('demand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=256)),
                ('cropimage', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('crop_price', models.IntegerField()),
                ('contact_no', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=150)),
                ('harvested_time', models.DateField()),
                ('demand_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
