# Generated by Django 5.1.5 on 2025-03-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='cropimage',
            new_name='crop_image',
        ),
    ]
