# Generated by Django 5.1.5 on 2025-03-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_rename_cropimage_demand_crop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='crop_image',
        ),
    ]
