# Generated by Django 5.1.5 on 2025-04-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
