# Generated by Django 5.1.5 on 2025-04-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='approved',
            new_name='status',
        ),
    ]
