# Generated by Django 5.1.5 on 2025-04-07 16:25

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_farmerprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprogress',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='farmerprogress',
            name='crop_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
