# Generated by Django 5.1.5 on 2025-04-07 16:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_farmerprogress_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprogress',
            name='crop_image',
        ),
        migrations.AddField(
            model_name='farmerprogress',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
